version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:8.4.3
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:z
      #- ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: "single-node"
  
  kibana:
    image: kibana:8.4.3
    volumes:
      - kibana:/usr/share/kibana
      #- ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  elasticsearch:
  kibana:
