version: '3'
services: 
    web:
        image: nginx:latest
        ports: 
            - "8000:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./src:/var/www
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./src:/var/www
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'admin'
            MYSQL_DATABASE: 'test'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
volumes:
    mysqldata: {}